version: "3.8"

services:
  db:
    image: postgres:15
    container_name: lotus_pg
    environment:
      POSTGRES_USER: lotus_admin
      POSTGRES_PASSWORD: LotusTravel2025
      POSTGRES_DB: lotus_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lotus_admin -d lotus_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    container_name: lotus_backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://lotus_admin:LotusTravel2025@db:5432/lotus_db
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: lotus_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  frontendadmin:
    build:
      context: ./frontendadmin
      dockerfile: Dockerfile.frontendadmin
    container_name: lotus_frontend_admin
    ports:
      - "5173:5173"
    environment:
      HOST: 0.0.0.0
    volumes:
      - ./frontendadmin:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  pgdata:
